### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by siiky**
The changes are hard to spot on the diffs, so I'll list them here. Please do let me know if you think any of my changes are wrong, maybe due to some misunderstanding on my part.

### VI

```diff
-saying, Lo, I am come to great estate, and have gotten more wisdom than
+saying, Lo, I have come to great estate, and have gotten more wisdom than
```

I'm not 100% sure about the following, because "mine" doesn't sound good to me, but at the same time it may be intentional.

```diff
-wisdom remained with me. And whatever mine eyes desired I kept not from
+wisdom remained with me. And whatever my eyes desired I kept not from
```

### XIV

```diff
-<p>In was then so necessary for me to believe in order to live that I
+<p>It was then so necessary for me to believe in order to live that I
```

```diff
-favourite books. Putting aside the miracles and regarding them as fables
+favourite book. Putting aside the miracles and regarding them as fables
```

### Afterword

```diff
-resting on one such support, by calves on another, and
+resting on one such support, my calves on another, and
```

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! Have you confirmed all of these with the page scans? https://catalog.hathitrust.org/Record/008973972

**Comment by siiky** [comment]
I haven't, no. I didn't know about that, I'll take a look!

**Comment by siiky** [comment]
I don't know how that site works, but I think I can't read the book? (looking at this question: https://www.hathitrust.org/help_digital_library#LimitedView)

**Comment by acabal** [comment]
It might not be accessible to non-US IP addresses

**Comment by siiky** [comment]
That would explain it

**Comment by acabal** [comment]
3 and 5 are typos, the rest are correct. Thanks!

**Pull request closed without merging**
