### PR TITLE
Add years to end of book and change o -> 0

### PR DESCRIPTION
**Pull request by brandonaut**
While the page scans use the letter o, I believe the number 0 was meant, for no one uses the letter o in mathematical equations.

### CODE REVIEW

**Comment by acabal** [comment]
For the years, can you put them in a `<footer>` tag, styled with

````
footer{
    margin-top: 1em;
    text-align: right;
}
````

Thanks!

**Comment by brandonaut** [comment]
Done!

**Comment by acabal** [comment]
Sorry--I meant keep the `<p>` tags, but wrap those tags in a `<footer>` element.  Usually we try to have a block-level element as direct descendant of those kinds of containers.

**Comment by brandonaut** [comment]
Ok, how does it look now?

**Comment by acabal** [comment]
Fantastic, thanks for all your hard work!

**Pull request merged**
